spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eubalaena?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: encrypt{file:${key-file}:mysql.username}
    password: encrypt{file:${key-file}:mysql.password}
